version: '3.8'
services:
  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/var/www/app
    depends_on:
      - php
  php:
    build:
      args:
        user: diego
        uid: 1000
      context: ./php
      dockerfile: Dockerfile    
    restart: unless-stopped
    deploy:
      replicas: 5
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/app.cnf:/etc/mysql/conf.d/app.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
