version: '3.8'
services:
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        depends_on:
            - php
    php:
        build: ./php
        restart: unless-stopped
        environment: 
            PHP_ENV: 'prod'
        volumes:
            - ./app:/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'new_app'
            MYSQL_USER: 'new_app'
            MYSQL_PASSWORD: 'new_app'
            MYSQL_DATABASE: 'new_app'
        ports:
            - 3306:3306
