version: '3.8'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/var/www/app
    depends_on:
      - php
  php:
    build:
      args:
        user: diego
        uid: 1000
      context: ./php
      dockerfile: Dockerfile    
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
